EXENAME = flights
OBJS = main.o algorithms.o read_airport.o read_routes.o


OBJS_DIR = .objs
CXX = clang++
CXXFLAGS = $(CS225) -std=c++1y -stdlib=libc++ -c -g -O0 -Wall -Wextra -pedantic
LD = clang++
LDFLAGS = -std=c++1y -stdlib=libc++ -lc++abi -lm

.PHONY: all test clean output_msg

all : $(EXENAME)


$(EXENAME): output_msg $(patsubst %.o, $(OBJS_DIR)/%.o, $(OBJS))
	$(LD) $(filter-out $<, $^) $(LDFLAGS) -o $@

$(OBJS_DIR)/%.o: %.cpp | $(OBJS_DIR)
	$(CXX) $(CXXFLAGS) $< -o $@

main.o : main.cpp algorithms.cpp read_airport.cpp read_routes.cpp
	$(CXX) $(CXXFLAGS) main.cpp

algorithms.o : algorithms.cpp algorithms.h
	$(CXX) $(CXXFLAGS) algorithms.cpp

read_airport.o: read_airport.cpp read_airport.h
	$(CXX) $(CXXFLAGS) read_airport.cpp

read_routes.o: read_routes.cpp read_routes.h
	$(CXX) $(CXXFLAGS) read_routes.cpp

clean :
	-rm -f *.o .txt $(EXENAME) test